// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SavingsApp.Data;

#nullable disable

namespace SavingsApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SavingsApp.Models.Entities.EventSaving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavingGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavingGoalId")
                        .IsUnique();

                    b.ToTable("EventSavings");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupSavingId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupSavingId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.GroupSaving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SavingGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavingGoalId")
                        .IsUnique();

                    b.ToTable("GroupSavings");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.SavingGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavingType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavingGoals");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.SavingTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContributionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SavingGoalId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavingGoalId");

                    b.HasIndex("UserId");

                    b.ToTable("SavingTransactions");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.TravelSaving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("int");

                    b.Property<decimal>("EquivalentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SavingGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavingGoalId")
                        .IsUnique();

                    b.ToTable("TravelSavings");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.EventSaving", b =>
                {
                    b.HasOne("SavingsApp.Models.Entities.SavingGoal", "SavingGoal")
                        .WithOne("EventSaving")
                        .HasForeignKey("SavingsApp.Models.Entities.EventSaving", "SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.GroupMember", b =>
                {
                    b.HasOne("SavingsApp.Models.Entities.GroupSaving", "GroupSaving")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupSavingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavingsApp.Models.Entities.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupSaving");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.GroupSaving", b =>
                {
                    b.HasOne("SavingsApp.Models.Entities.SavingGoal", "SavingGoal")
                        .WithOne("GroupSaving")
                        .HasForeignKey("SavingsApp.Models.Entities.GroupSaving", "SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.SavingGoal", b =>
                {
                    b.HasOne("SavingsApp.Models.Entities.User", "User")
                        .WithMany("SavingGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.SavingTransaction", b =>
                {
                    b.HasOne("SavingsApp.Models.Entities.SavingGoal", "SavingGoal")
                        .WithMany("SavingTransactions")
                        .HasForeignKey("SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SavingsApp.Models.Entities.User", "User")
                        .WithMany("SavingTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SavingGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.TravelSaving", b =>
                {
                    b.HasOne("SavingsApp.Models.Entities.SavingGoal", "SavingGoal")
                        .WithOne("TravelSaving")
                        .HasForeignKey("SavingsApp.Models.Entities.TravelSaving", "SavingGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingGoal");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.GroupSaving", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.SavingGoal", b =>
                {
                    b.Navigation("EventSaving")
                        .IsRequired();

                    b.Navigation("GroupSaving")
                        .IsRequired();

                    b.Navigation("SavingTransactions");

                    b.Navigation("TravelSaving")
                        .IsRequired();
                });

            modelBuilder.Entity("SavingsApp.Models.Entities.User", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("SavingGoals");

                    b.Navigation("SavingTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
